build: disable rst strict check due to implicit target name bug
The following is quoted from the following pull request. Please reference it for additional details. https://github.com/edx/commerce-coordinator/pull/29

"rST duplicate implicit target name
===================================
... [T]he GitHub action fails due to an error like:

docs run-test: commands[5] | python setup.py check --restructuredtext --strict
...
warning: check: Duplicate implicit target name: "...".
...
ERROR: InvocationError for command /home/runner/work/commerce-coordinator/commerce-coordinator/.tox/docs/bin/python setup.py check --restructuredtext --strict (exited with code 1)
This docs test lints all rST in the repository (as opposed to only the generated rST in the docs folder). Unfortunately, it:

Has a bug which elevates INFO-level lint messages to WARN-level lint messages.
Will be eventually deprecated because it is part of the distutils library.
This PR removes --strict from the command invocation, thus printing out the lint results but not making the build red because of any errors."